Add missing header for C++23
C++23 removed certain transitive includes so you need to add algorithm
explicitly for std::any_of.

Error:
external/grpc-grpc/src/core/util/glob.cc:21:15: error: no member named
'any_of' in namespace 'std'
   21 |   return std::any_of(trace_glob.begin(), trace_glob.end(),

Bug: 429048222
Test: lunch aosp_cf_x86_64_only_phone-trunk_staging-userdebug && m
Change-Id: I6073730b9230e5ace748a4da0c82d544fb517b4d